### ISSUE TITLE
Error when upgrading when using OpenZeppelinTransparentProxy

### ISSUE THREAD

**Issue by marcelomorgado** [wighawag/hardhat-deploy#103]
Hi,
I've faced an issue when trying to upgrade my contract, here are the details:

- Versions
    "ethers": "5.1.0",
    "hardhat": "2.1.2",
    "hardhat-deploy": "0.7.5",
    "hardhat-deploy-ethers": "0.3.0-beta.7"

- Deploy script
```
  await deploy("SomeContract", {
    from: deployer,
    proxy: {
      methodName: "initialize",
      proxyContract: "OpenZeppelinTransparentProxy",
    },
    args: [x, y, z],
    log: true,
  });
```

- Error
```
reusing "DefaultProxyAdmin" at 0x9689460D66E1F10675e9829ee38010E08818dc6E
deploying "SomeContract_Implementation" (tx: 0x6ed0ffa61948345de7a6d8f2fe9fc8ddae7f7080c4aaba97baa417106627c97e)...: deployed at 0xa6fF1A8dDE6eE2a9752Be2F739458A964930Dfc8 with 2266318 gas
executing DefaultProxyAdmin.upgradeAndCallAn unexpected error occurred:

Error: ERROR processing /repodir/packages/contracts/deploy/02_gateway.ts:
Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"name":"ProviderError","code":-32000}, method="estimateGas", transaction={"from":"0xA8E953ac33efEe299515f7100c4d644Cda8AD183","to":"0x9689460D66E1F10675e9829ee38010E08818dc6E","data":"0x9623609d000000000000000000000000631eb573aef0c0c3a639d621aaaccd2e34dc08aa000000000000000000000000a6ff1a8dde6ee2a9752be2f739458a964930dfc800000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000064c0c53b8b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000005e4ec3dc967b71a5ad8654baa33663cb46513a2f0000000000000000000000005e4ec3dc967b71a5ad8654baa33663cb46513a2f00000000000000000000000000000000000000000000000000000000","accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.1.2)
    at Logger.makeError (/repodir/node_modules/hardhat-deploy/node_modules/@ethersproject/logger/src.ts/index.ts:205:28)
    at Logger.throwError (/repodir/node_modules/hardhat-deploy/node_modules/@ethersproject/logger/src.ts/index.ts:217:20)
    at checkError (/repodir/node_modules/hardhat-deploy/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:76:16)
    at Web3Provider.<anonymous> (/repodir/node_modules/hardhat-deploy/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:512:20)
    at step (/repodir/node_modules/hardhat-deploy/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/repodir/node_modules/hardhat-deploy/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/repodir/node_modules/hardhat-deploy/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at DeploymentsManager.executeDeployScripts (/repodir/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1009:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "deploy" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

- Note

It's trying to call the `upgradeAndCall` function. I was able to upgrade my contract by calling the `upgrade` function manually. Is there a way to set which function to use?

Thanks

**Comment by wighawag** [comment]
it is using upgradeAndCall because you are passing the `methodName`

**Comment by marcelomorgado** [comment]
> it is using upgradeAndCall because you are passing the `methodName`

You're right, thanks. Worked now.
