### ISSUE TITLE
`OpenZeppelinTransparentProxy` deployment isn't working

### ISSUE THREAD

**Issue by marcelomorgado** [wighawag/hardhat-deploy#158]
Hi, since the latest dependency upgrades my deployment script isn't working anymore.

Error:
```sh
An unexpected error occurred:

Error: ERROR processing /home/marcelo/.../contracts/deploy/deploy_script.ts:
Error: The number of arguments passed to not match the number of argument in the implementation constructor.
Please specify the correct number of arguments as part of the deploy options: "args"
    at _deployViaEIP173Proxy (/home/cmarcelo/.../node_modules/hardhat-deploy/src/helpers.ts:1014:13)
    at DeploymentsManager.executeDeployScripts (/home/cmarcelo/.../node_modules/hardhat-deploy/src/DeploymentsManager.ts:1052:19)
    at DeploymentsManager.runDeploy (/home/cmarcelo/.../node_modules/hardhat-deploy/src/DeploymentsManager.ts:885:5)
    at Environment._runTaskDefinition (/home/marcelo/.../contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/home/marcelo/.../contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at SimpleTaskDefinition.action (/home/cmarcelo/.../node_modules/hardhat-deploy/src/index.ts:528:32)
    at Environment._runTaskDefinition (/home/marcelo/.../contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/home/marcelo/.../contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at SimpleTaskDefinition.action (/home/cmarcelo/.../node_modules/hardhat-deploy/src/index.ts:605:5)
    at Environment._runTaskDefinition (/home/marcelo/.../contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/home/marcelo/.../contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
error Command failed with exit code 1.
```

Contract's `initialize` function interface:

```solidity
function initialize(ISomeInterface _a, address _b, address _c) public initializer
```

My script:
```typescript
 await deploy("Contract", {
    from: deployer,
    proxy: {
      methodName: "initialize",
      proxyContract: "OpenZeppelinTransparentProxy",
    },
    args: [A, B, C],
    log: true,
  });
```

Related dependency versions:
```json
    "@nomiclabs/ethereumjs-vm": "4.2.2",
    "@nomiclabs/hardhat-ethers": "2.0.2",
    "@openzeppelin/contracts": "3.4.1",
    "@openzeppelin/contracts-upgradeable": "3.4.0",
    "ethers": "5.4.1",
    "hardhat": "2.4.3",
    "hardhat-deploy": "0.8.11",
    "hardhat-deploy-ethers": "0.3.0-beta.7",
```

Let me know if you need more info,

Thanks!

**Comment by Dylan-Kerler** [comment]
I'm not sure if this is a bug or intended behaviour but this should be a sufficient workaround:

```javascript
 await deploy("Contract", {
    from: deployer,
    proxy: {
      proxyContract: "OpenZeppelinTransparentProxy",
      execute: {
        methodName: "initialize",
        args: [A, B, C],
      }
    },
    log: true,
  });
```

**Comment by marcelomorgado** [comment]
Hey @Dylan-Kerler thanks!
That worked! I'm not sure but seems that the interface changed then. If it's the case would be useful to update the docs.
FYI @wighawag

**Comment by wighawag** [comment]
Thanks for the report, indeed if I recall I made it more strict. 
Before if the constructor had zero args (probably your case) hardhat-deploy was not complaining and use the args field for the initialise function. now you need to explictly set it in the `execute` field
