### ISSUE TITLE
Importing external deploy scripts in Typescript fails

### ISSUE THREAD

**Issue by suranap** [wighawag/hardhat-deploy#201]
Trying to [import](https://github.com/wighawag/hardhat-deploy#importing-deployment-from-other-projects-with-truffle-support) another project's deploy script and artifacts using `external`.  The deploy script is written in Typescript. Get the error below when I call `hardhat deploy`. 

Can we use deploy scripts written in Typescript? 

```
Error HH604: Error running JSON-RPC server: ERROR processing skip func of /home/michael/work/4ire/github/protocol-dev-bsc/node_modules/@myprotocol/protocol-npm-package/deploy/001_deploy_contracts.ts:
/home/michael/work/4ire/github/protocol-dev-bsc/node_modules/@myprotocol/protocol-npm-package/deploy/001_deploy_contracts.ts:1
import {HardhatRuntimeEnvironment} from 'hardhat/types';
^^^^^^

SyntaxError: Cannot use import statement outside a module
at Object.compileFunction (node:vm:355:18)
at wrapSafe (node:internal/modules/cjs/loader:1039:15)
at Module._compile (node:internal/modules/cjs/loader:1073:27)
at Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
at Object.require.extensions. [as .ts] (/home/michael/work/4ire/github/protocol-dev-bsc/node_modules/ts-node/src/index.ts:1300:43)
at Module.load (node:internal/modules/cjs/loader:989:32)
at Function.Module._load (node:internal/modules/cjs/loader:829:14)
at Module.require (node:internal/modules/cjs/loader:1013:19)
at require (node:internal/modules/cjs/helpers:93:18)
at DeploymentsManager.executeDeployScripts (/home/michael/work/4ire/github/protocol-dev-bsc/node_modules/hardhat-deploy/src/DeploymentsManager.ts:947:22)
```

**Comment by wighawag** [comment]
You have to use a compiled-to-js version of your external deploy script, see for example how this repo does it : https://github.com/wighawag/universal-forwarder/tree/main/export/deploy
