### ISSUE TITLE
Error when deploy ERC20Upgradeable, Openzepplin Proxy

### ISSUE THREAD

**Issue by hoangtrung99** [wighawag/hardhat-deploy#212]
The deploy seems to be successful. But when i run the script the error occurs again and if i use `upgrades.deployProxy` everything works fine, please help me check.
My deploy script
```js
import { DeployFunction } from "hardhat-deploy/dist/types";
import { NamedAccounts } from "../hardhat.config";
import { HardhatRuntimeEnvironment } from "hardhat/types";

const deployFn: DeployFunction = async (hre: HardhatRuntimeEnvironment) => {
  const { deployments, getNamedAccounts } = hre;
  const { deploy } = deployments;

  const { deployer } = (await getNamedAccounts()) as NamedAccounts;

  await deploy("MAIToken", {
    from: deployer,
    log: true,
    proxy: {
      methodName: "initialize",
      proxyContract: "OpenZeppelinTransparentProxy",
    },
  });
};

export default deployFn;

deployFn.tags = ["mai"];

```

My script
```js
import { ethers } from "hardhat";
import { execute, getContracts } from "../utils";

const nativeToken = "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE";

// 0.0001 native token = 1 MAI
const nativeTokenRate = 0.0001;
// 20 WKGR = 1 MAI
const wkgrRate = 20;

async function main() {
  const { mai } = await getContracts(true);
  // Set native token rate 0.0001 native token = 1 MAI
  const setNativeRate = await mai.setBuyRate(
    nativeToken,
    ethers.utils.parseEther(nativeTokenRate.toString())
  );
  await setNativeRate.wait();
  console.log("Set native token rate success!", nativeToken, nativeTokenRate);

  const buy = await mai.buyMaiByNativeToken({
    value: ethers.utils.parseEther("0.001"),
  });
  await buy.wait();

  console.log("Buy success!");

  const balances = await mai.balanceOf(
    "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  );
  console.log(balances.toString());

  //   const _nativeRate = await mai.getBuyRate(nativeToken);
  //   console.log("Native token rate", _nativeRate.toNumber());
}

execute(main);

```
I get the following error when calling the function `balanceOf` and `getBuyrate`
When i run the script the error occurs again and if i use `upgrades.deployProxy` everything works fine.

```zsh
❯ npx hardhat run scripts/set_mai_buy_rate.ts
No need to generate any newer typings.
Set native token rate success! 0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE 0.0001
Buy success!
Error: call revert exception (method="balanceOf(address)", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.4.1)
    at Logger.makeError (/Users/hoangtrung/solashi/gacha-contract-2/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
    at Logger.throwError (/Users/hoangtrung/solashi/gacha-contract-2/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)
    at Interface.decodeFunctionResult (/Users/hoangtrung/solashi/gacha-contract-2/node_modules/@ethersproject/abi/src.ts/interface.ts:425:23)
    at Contract.<anonymous> (/Users/hoangtrung/solashi/gacha-contract-2/node_modules/@ethersproject/contracts/src.ts/index.ts:332:44)
    at step (/Users/hoangtrung/solashi/gacha-contract-2/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/Users/hoangtrung/solashi/gacha-contract-2/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at fulfilled (/Users/hoangtrung/solashi/gacha-contract-2/node_modules/@ethersproject/contracts/lib/index.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:526:9) {
  reason: null,
  code: 'CALL_EXCEPTION',
  method: 'balanceOf(address)',
  errorArgs: null,
  errorName: null,
  errorSignature: null,
  address: '0xa513E6E4b8f2a923D98304ec87F64353C4D5C853',
  args: [ '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266' ],
  transaction: {
    data: '0x70a08231000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266',
    to: '0xa513E6E4b8f2a923D98304ec87F64353C4D5C853',
    from: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266',
    gasLimit: BigNumber { _hex: '0x01bad9d8', _isBigNumber: true }
  }
}
```

My contract is simple
```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/utils/structs/EnumerableSet.sol";
import "@openzeppelin/contracts-upgradeable/token/ERC20/ERC20Upgradeable.sol";
import "@openzeppelin/contracts-upgradeable/token/ERC20/IERC20Upgradeable.sol";
import "@openzeppelin/contracts-upgradeable/utils/math/SafeMathUpgradeable.sol";

contract MAIToken is ERC20Upgradeable {
    using EnumerableSet for EnumerableSet.AddressSet;
    using SafeMathUpgradeable for uint256;

    mapping(address => uint256) buyRate;


    function initialize() public initializer {
        __ERC20_init("MAIToken", "MAI");
    }
...
```

**Comment by hoangtrung99** [comment]
It seems that it only happens when I use network hardhat (despite deploying with --reset flag), when I deploy it to another network there is no error

**Comment by wighawag** [comment]
@hoangtrung99 sorry for the late reply

if you do not specify --network, it will use the default network, which by default is the internal `hardhat` network

I still not sure what error you get, if you have a repdocutible repo, I could look at it

**Comment by hoangtrung99** [comment]
@wighawag I want to use it on harthat intranet, but it got the above error, when i try to upload it to another network(mumbai, polygon) the error didn't happen. I still haven't figured out why, but it just fails on the network hardhat.
