### ISSUE TITLE
ERROR: deterministic deployment  on avax

### ISSUE THREAD

**Issue by Aniket965** [wighawag/hardhat-deploy#237]
Hey @wighawag, i am using deterministic deployment on avax, but this signed tx is not supported over rpc to make the deployerFactory, can you help 🙂 !

```
error: ProviderError: only replay-protected (EIP-155) transactions allowed over RPC
      at HttpProvider.request (/Users/arth/Documents/movrnetwork/aggregator-contracts/node_modules/hardhat/src/internal/core/providers/http.ts:49:19)
      at HDWalletProvider.request (/Users/arth/Documents/movrnetwork/aggregator-contracts/node_modules/hardhat/src/internal/core/providers/accounts.ts:168:34)
      at processTicksAndRejections (internal/process/task_queues.js:95:5),
  method: 'sendTransaction',
  transaction: {
    nonce: 0,
    gasPrice: BigNumber { _hex: '0x174876e800', _isBigNumber: true },
    gasLimit: BigNumber { _hex: '0x0186a0', _isBigNumber: true },
    to: null,
    value: BigNumber { _hex: '0x00', _isBigNumber: true },
    data: '0x604580600e600039806000f350fe7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe03601600081602082378035828234f58015156039578182fd5b8082525050506014600cf3',
    chainId: 0,
    v: 27,
    r: '0x2222222222222222222222222222222222222222222222222222222222222222',
    s: '0x2222222222222222222222222222222222222222222222222222222222222222',
    from: '0x3fAB184622Dc19b6109349B94811493BF2a45362',
    hash: '0xeddf9e61fb9d8f5111840daef55e5fde0041f5702856532cdbb5a02998033d26',
    type: null,
    confirmations: 0
  },
  transactionHash: '0xeddf9e61fb9d8f5111840daef55e5fde0041f5702856532cdbb5a02998033d26'
}
```

**Comment by wighawag** [comment]
I am not familiar with avax, but you might need to implement your own deployer factory, see : https://github.com/wighawag/hardhat-deploy/pull/190 that let you implement that

But note that this will means addresses on avax will not be the same as on ethereum mainnet
