### ISSUE TITLE
deployScript.func is not a function

### ISSUE THREAD

**Issue by PatrickAlphaC** [wighawag/hardhat-deploy#272]
**Describe the bug**

When calling `yarn hardhat deploy` on a new typescript setup, you get the following error

```
deployScript.func is not a function
```

**To Reproduce**
1. `npx hardhat`
Choose the typescript option to setup a new typescript project.

2. Add some contracts, and a simple deploy.ts in your `deploy` folder

Something like:

```javascript
import { HardhatRuntimeEnvironment } from "hardhat/types";
import { DeployFunction } from "hardhat-deploy/types";

const deployToken: DeployFunction = async function (
  hre: HardhatRuntimeEnvironment
) {}
```

3. Run `yarn hardhat deploy`

**Expected behavior**

**versions**
 - hardhat-deploy`0.10.4`
 - hardhat `2.8.3`
 - nodejs `v14.17.0`

Full error:

```
Error: ERROR processing XXXX/deploy/01-token.ts:
TypeError: deployScript.func is not a function
    at DeploymentsManager.executeDeployScripts (XXXX/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1220:41)
    at DeploymentsManager.runDeploy (XXXX/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1053:16)
    at async SimpleTaskDefinition.action (XXXX/node_modules/hardhat-deploy/src/index.ts:422:5)
    at async Environment._runTaskDefinition (XXXX/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at async Environment.run (XXXX/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at async SimpleTaskDefinition.action (XXXX/node_modules/hardhat-deploy/src/index.ts:568:32)
    at async Environment._runTaskDefinition (XXXX/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at async Environment.run (XXXX/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at async SimpleTaskDefinition.action (XXXX/node_modules/hardhat-deploy/src/index.ts:653:5)
    at async Environment._runTaskDefinition (XXXX/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at DeploymentsManager.executeDeployScripts (XXXX/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1223:19)
    at DeploymentsManager.runDeploy (XXXX/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1053:16)
    at async SimpleTaskDefinition.action (XXXX/node_modules/hardhat-deploy/src/index.ts:422:5)
    at async Environment._runTaskDefinition (XXXX/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at async Environment.run (XXXX/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at async SimpleTaskDefinition.action (XXXX/node_modules/hardhat-deploy/src/index.ts:568:32)
    at async Environment._runTaskDefinition (XXXX/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at async Environment.run (XXXX/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at async SimpleTaskDefinition.action (XXXX/node_modules/hardhat-deploy/src/index.ts:653:5)
    at async Environment._runTaskDefinition (XXXX/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
```

package.json

```
{
  "name": "hardhat-project",
  "dependencies": {
    "@nomiclabs/hardhat-etherscan": "^3.0.0",
    "@nomiclabs/hardhat-waffle": "^2.0.2",
    "@openzeppelin/contracts": "^4.4.2",
    "@typechain/ethers-v5": "^9.0.0",
    "@typechain/hardhat": "^4.0.0",
    "dotenv": "^16.0.0",
    "hardhat-deploy": "^0.10.4",
    "hardhat-gas-reporter": "^1.0.7",
    "prettier": "^2.5.1",
    "prettier-plugin-solidity": "^1.0.0-beta.19",
    "solhint": "^3.3.6",
    "solidity-coverage": "^0.7.18",
    "ts-node": "^10.4.0",
    "typescript": "^4.5.5"
  },
  "devDependencies": {
    "@nomiclabs/hardhat-ethers": "npm:hardhat-deploy-ethers",
    "ethers": "^5.5.4",
    "hardhat": "^2.8.3",
    "typechain": "^7.0.0"
  }
}
```

**Comment by PatrickAlphaC** [comment]
I'm a dunce. I forgot to export the deploy function. 

```javascript
import { HardhatRuntimeEnvironment } from "hardhat/types";
import { DeployFunction } from "hardhat-deploy/types";

const deployToken: DeployFunction = async function (
  hre: HardhatRuntimeEnvironment
) {}
export default deployToken
```

**Comment by PatrickAlphaC** [comment]
Maybe we could make the error a little nicer
