### ISSUE TITLE
deterministicDeployment throughs error when used with string for salt

### ISSUE THREAD

**Issue by radeksvarz** [wighawag/hardhat-deploy#273]
**To Reproduce**
```
await deploy('Registry', {
    from: deployer,
    contract: "Registry",
    deterministicDeployment: "abcdefghijkl",
```

hh deploy raises:

```
Error: invalid arrayify value (argument="value", value="abcdefghijkl", code=INVALID_ARGUMENT, version=bytes/5.5.0)
    at Logger.makeError (/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
    at Logger.throwError (/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)
    at Logger.throwArgumentError (/node_modules/@ethersproject/logger/src.ts/index.ts:241:21)
    at arrayify (/node_modules/@ethersproject/bytes/src.ts/index.ts:138:19)
    at Object.zeroPad (/node_modules/@ethersproject/bytes/src.ts/index.ts:173:13)
    at fetchIfDifferent (/node_modules/hardhat-deploy/src/helpers.ts:855:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async _deployOne (/node_modules/hardhat-deploy/src/helpers.ts:932:24)
```

I tested the relevance of all other arguments, and the error is raised by this one in the case of string parameter. Boolean works.

**versions**
"hardhat-deploy": "^0.10.4",
"hardhat": "^2.7.0",
├── ts-node@10.4.0
├── typechain@5.2.0
└── typescript@4.5.2

**Comment by wighawag** [comment]
It needs to be a bytes32 string like "0xfdeffdeffdeffdeffdeffdeffdeffdeffdeffdeffdeffdeffdeffdeffdeffdef"

**Comment by radeksvarz** [comment]
I can confirm that with `ethers.utils.formatBytes32String("some short text")` it works.
I suggest to update some template with that.

**Comment by radeksvarz** [comment]
For anyone looking onto this issue:

`deterministicDeployment` uses onchain proxy for the deployment of the contract. 

Secondary impact is that the `msg.sender` within the deployed contract **is in fact the proxy** and not the deployer account.

Example - when the contract uses openzeppelin's ownable with `Ownable()` initiation in the constructor.
