### ISSUE TITLE
Allow constructor arguments to be modular with proxyadmin contracts

### ISSUE THREAD

**Issue by PatrickAlphaC** [wighawag/hardhat-deploy#283]
Right now I can deploy an openzeppelin transparent proxy'd contract like so:

```javascript
    const { box } = await deploy("Box", {
        from: deployer,
        args: [],
        log: true,
        waitConfirmations: waitBlockConfirmations,
        proxy: {
            proxyContract: "OpenZeppelinTransparentProxy",
            viaAdminContract: {
                name: "ProxyAdmin",
                artifact: "ProxyAdmin",
            },
        },
    })
```

Where I have a `ProxyAdmin` contract:

```javascript
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.4;

import "@openzeppelin/contracts/proxy/transparent/ProxyAdmin.sol";
}

```

However, running this as such, I will get this error: 

```
Error: ERROR processing /<DIR>/deploy/01-deploy-box.js:
Error: expected 0 constructor arguments, got 1
    at _deploy (/<DIR>/node_modules/hardhat-deploy/src/helpers.ts:560:13)
    at _deployOne (/<DIR>/node_modules/hardhat-deploy/src/helpers.ts:934:16)
    at _deployViaProxy (/<DIR>/node_modules/hardhat-deploy/src/helpers.ts:1378:30)
    at Object.module.exports [as func] (/<DIR>/deploy/01-deploy-box.js:19:21)
    at DeploymentsManager.executeDeployScripts (/<DIR>/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1220:22)
    at DeploymentsManager.runDeploy (/<DIR>/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1053:5)
    at SimpleTaskDefinition.action (/<DIR>/node_modules/hardhat-deploy/src/index.ts:422:5)
    at Environment._runTaskDefinition (/<DIR>/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/<DIR>/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at SimpleTaskDefinition.action (/<DIR>/node_modules/hardhat-deploy/src/index.ts:568:32)
    at DeploymentsManager.executeDeployScripts (/<DIR>/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1223:19)
    at DeploymentsManager.runDeploy (/<DIR>/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1053:5)
    at SimpleTaskDefinition.action (/<DIR>/node_modules/hardhat-deploy/src/index.ts:422:5)
    at Environment._runTaskDefinition (/<DIR>/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/<DIR>/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at SimpleTaskDefinition.action (/<DIR>/node_modules/hardhat-deploy/src/index.ts:568:32)
    at Environment._runTaskDefinition (/<DIR>/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/<DIR>/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at SimpleTaskDefinition.action (/<DIR>/node_modules/hardhat-deploy/src/index.ts:653:5)
    at Environment._runTaskDefinition (/<DIR>/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
```

It seems to stem from the `_deployViaProxy` which will always pass the `owner` as an argument. It would be nice it that could be modularized.

Unless I'm not understanding how to deploy a ProxyAdmin with the OZ transparent proxy correctly. 

Thanks!

**Comment by PatrickAlphaC** [comment]
My current workaround is as such:

```javascript
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.4;

import "@openzeppelin/contracts/proxy/transparent/ProxyAdmin.sol";

contract BoxProxyAdmin is ProxyAdmin {
  constructor(address owner) ProxyAdmin(){
      // We just need this for our hardhat tooling right now
  }
}
```

So we just pass a constructor parameter that we won't use, and call the constructor of ProxyAdmin anyways. Seems like a bit of a waste of gas though.

**Comment by wighawag** [comment]
You can deploy your proxy admin first and then refers to ti

```
await deploy('MyProxyAdmin', ...

await deploy("Box", {
        from: deployer,
        args: [],
        log: true,
        waitConfirmations: waitBlockConfirmations,
        proxy: {
            proxyContract: "OpenZeppelinTransparentProxy",
            viaAdminContract: {
                name: "MyProxyAdmin"
            },
        },
    })
```

**Comment by wighawag** [comment]
by the way re gas, you might want to consider using `OptimizedTransparentProxy` instead of `OpenZeppelinTransparentProxy`

**Comment by PatrickAlphaC** [comment]
True, I'll play with this. Thanks!
