### ISSUE TITLE
If proxy upgrade fails, it does not try again

### ISSUE THREAD

**Issue by rhlsthrm** [wighawag/hardhat-deploy#316]
**Describe the bug**
I found an issue where my proxy upgrade was failing for some reason (still unknown). However the bigger issue is that hardhat-deploy did not detect that it failed to upgrade on the next run. The first time I ran the deploy script to upgrade, I got this error:

```
deploying "ConnextHandler_Implementation" (tx: 0x908e30d8914bfac895ca92666f90ee6eb56b048315bd088aecaa11d97d611d92)...: deployed at 0x77662ce614fa85bAa4AF2912Cf104561EB712571 with 4489249 gas
An unexpected error occurred:

Error: ERROR processing /Users/rahul/connext/repos/nxtp/packages/deployments/contracts/deploy/02_deployConnext.ts:
Error: To change owner/admin, you need to call the proxy directly, it currently is 0x8b48A9E32D332E4894e3946d7036B64B5Aad14a8
    at _deployViaProxy (/Users/rahul/connext/repos/nxtp/node_modules/hardhat-deploy/src/helpers.ts:1465:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.func (/Users/rahul/connext/repos/nxtp/packages/deployments/contracts/deploy/02_deployConnext.ts:92:19)
    at async DeploymentsManager.executeDeployScripts (/Users/rahul/connext/repos/nxtp/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1219:22)
    at async DeploymentsManager.runDeploy (/Users/rahul/connext/repos/nxtp/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1052:5)
    at async SimpleTaskDefinition.action (/Users/rahul/connext/repos/nxtp/node_modules/hardhat-deploy/src/index.ts:422:5)
    at async Environment._runTaskDefinition (/Users/rahul/connext/repos/nxtp/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at async Environment.run (/Users/rahul/connext/repos/nxtp/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at async SimpleTaskDefinition.action (/Users/rahul/connext/repos/nxtp/node_modules/hardhat-deploy/src/index.ts:568:32)
    at async Environment._runTaskDefinition (/Users/rahul/connext/repos/nxtp/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at DeploymentsManager.executeDeployScripts (/Users/rahul/connext/repos/nxtp/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1222:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DeploymentsManager.runDeploy (/Users/rahul/connext/repos/nxtp/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1052:5)
    at async SimpleTaskDefinition.action (/Users/rahul/connext/repos/nxtp/node_modules/hardhat-deploy/src/index.ts:422:5)
    at async Environment._runTaskDefinition (/Users/rahul/connext/repos/nxtp/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at async Environment.run (/Users/rahul/connext/repos/nxtp/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at async SimpleTaskDefinition.action (/Users/rahul/connext/repos/nxtp/node_modules/hardhat-deploy/src/index.ts:568:32)
    at async Environment._runTaskDefinition (/Users/rahul/connext/repos/nxtp/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at async Environment.run (/Users/rahul/connext/repos/nxtp/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at async SimpleTaskDefinition.action (/Users/rahul/connext/repos/nxtp/node_modules/hardhat-deploy/src/index.ts:653:5)
```

I did not know what happened, so I ran it again. On the next run, it acted as if everything was fine:
```
Deploying connext...
reusing "ConnextProxyAdmin" at 0x166b6A5f5D7ab988B9e769Bf0BfdE149408e968b
reusing "ConnextHandler_Implementation" at 0xBB22c77655d4e4E765E11B8727A70c003Ba64528
```

However, I later found out (after much debugging) that the proxy was pointing at the old implementation and never got upgraded. I manually changed the admin of the proxy at the address in the first error and then I deleted the implementation deployment and redeployed, and finally it worked properly.

**To Reproduce**
Unfortunately not clear how, but our code is open source here: https://github.com/connext/nxtp/tree/main/packages/deployments/contracts/deploy

**Expected behavior**
The script does not seem to check the proxy implementation address using the proxy admin. If it did that it could detect when the proxy needed to be upgraded.

**versions**
 - hardhat-deploy ^0.11.2
 - hardhat ^2.9.1
 - nodejs v16.15.0

**Additional context**

**Comment by helderjnpinto** [comment]
Same issue here, any updates on this ... i only notice this on mainnet!
