### ISSUE TITLE
Fixtures Don't Seem to Work

### ISSUE THREAD

**Issue by hickscorp** [wighawag/hardhat-deploy#328]
We are migrating a hardhat project to use `hardhat-deploy`, as we wanted to also leverage the `Diamond` pattern baked into `hardhat-deploy`.

Consider the following test code:

```ts
import * as chai from 'chai';
import { expect } from 'chai';
import { deployments, ethers } from 'hardhat';
import { FakeContract, smock } from '@defi-wonderland/smock';
import { Spc, Fast, Exchange } from '../typechain';
import { SignerWithAddress } from 'hardhat-deploy-ethers/signers';
chai.use(smock.matchers);

describe('FastAccessFacet', () => {
  let
    deployer: SignerWithAddress,
    spcMember: SignerWithAddress,
    governor: SignerWithAddress;
  let spc: FakeContract<Spc>,
    exchange: FakeContract<Exchange>,
    fast: Fast,
    governedFast: Fast,
    spcMemberFast: Fast;
  let deployFast: (options?: unknown) => Promise<Fast>;

  before(async () => {
    // Keep track of a few signers.
    [deployer, spcMember, governor] = await ethers.getSigners();
    // Mock an SPC and a FAST.
    spc = await smock.fake('Spc');
    exchange = await smock.fake('Exchange');

    deployFast = deployments.createFixture(async (hre) => {
      const deploy = await deployments.diamond.deploy('Fast', {
        from: deployer.address,
        owner: spcMember.address,
        facets: ['FastFacet', 'FastAccessFacet', 'FastTokenFacet', 'FastHistoryFacet'],
        execute: {
          contract: 'FastInitFacet', methodName: 'initialize', args: [{
            spc: spc.address,
            exchange: exchange.address,
            governor: governor.address,
            name: 'Better, Stronger, FASTer.',
            symbol: 'FST',
            decimals: 18,
            hasFixedSupply: true,
            isSemiPublic: true
          }]
        }
      });

      return await ethers.getContractAt('Fast', deploy.address) as Fast;
    });
  });

  beforeEach(async () => {
    spc.isMember.returns(false);
    spc.isMember.whenCalledWith(spcMember.address).returns(true);

    fast = await deployFast();
    governedFast = fast.connect(governor);
    spcMemberFast = fast.connect(spcMember);
  });

  describe('IHasGovernors implementation', async () => {
    describe('addGovernor', async () => {
      it('requires SPC membership (anonymous)', async () => {
        const subject = fast.addGovernor(ethers.constants.AddressZero);
        // Check that the registry
        await expect(subject).to.be
          .revertedWith('Missing SPC membership');
      });
    });
  });
});
```

This code behaves differently whether we  clean the `deployments/hardhat` folder before running it.
The first time, it runs (as long as `deployments/hardhat/` is **empty**).
But for subsequent runs we get:
```
     Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="facets()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.6.3)
      at Logger.makeError (node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
      at Logger.throwError (node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
      at Interface.decodeFunctionResult (node_modules/@ethersproject/abi/src.ts/interface.ts:427:23)
      at Contract.<anonymous> (node_modules/@ethersproject/contracts/src.ts/index.ts:400:44)
      at step (node_modules/@ethersproject/contracts/lib/index.js:48:23)
      at Object.next (node_modules/@ethersproject/contracts/lib/index.js:29:53)
      at fulfilled (node_modules/@ethersproject/contracts/lib/index.js:20:58)
```

**Comment by hickscorp** [comment]
Another problem, related to the same thing - if I use fixtures in different test files, but they all call `deployments.diamond.deploy('Fast', ...)`, the error above is thrown.
If I use a unique name per test file for the diamond, it works...

**Comment by wighawag** [comment]
hmm, deployments/hardhat should never exit. can you share your config ?

**Comment by hickscorp** [comment]
import 'dotenv/config';
import * as dotenv from 'dotenv';
import { HardhatUserConfig } from 'hardhat/config';
import '@typechain/hardhat';
import 'hardhat-deploy';
import 'hardhat-deploy-ethers';
import 'hardhat-diamond-abi';
import 'solidity-coverage';
import 'hardhat-gas-reporter';

// Loads `.env` file into `process.env`.
dotenv.config();

// Import all of our tasks here!
import './tasks/accounts';
...

const config: HardhatUserConfig = {
  solidity: {
    version: '0.8.4',
    settings: {
      outputSelection: {
        '*': {
          '*': ['storageLayout']
        }
      }
    }
  },
  diamondAbi: {
    name: 'Fast',
    include: [
      'IERC173',
      'IERC165',
      'IDiamondCut',
      'IDiamondLoupe',
      ...
    ]
  },
  networks: {
    hardhat: {
      live: false,
      saveDeployments: true,
      tags: ['test', 'local']
    },
    localhost: {
      live: false,
      saveDeployments: true,
      tags: ['local'],
    }
  },
  namedAccounts: {
    deployer: {
      hardhat: 0,
      localhost: 0
    },
    spcMember: {
      hardhat: 1,
      localhost: 1
    },
    fastGovernor: {
      hardhat: 2,
      localhost: 2
    }
  },
  typechain: {
    outDir: 'typechain',
    target: 'ethers-v5',
  },
  gasReporter: {
    enabled: process.env.REPORT_GAS !== undefined,
    gasPrice: 21
  }
};
export default config;

**Comment by wighawag** [comment]
Ok, the issue arise because you save the deployment via `saveDeployments: true,`

It should never be needed for hardhat as it is an in memory network

**Comment by hickscorp** [comment]
If I don't, I have no way to make my tests pass.

**Comment by hickscorp** [comment]
@wighawag if you want to reproduce:

- Have two test files.
- Create a fixture in each test file, deploying the same diamond.

Try running `yarn hardhat test` - the first test file will pass, the second will fail.
But if you run `yarn hardhat test file1.test.ts && yarn hardhat test file2.test.ts`, both will pass.
For us it's a problem, because running test files one by one doesn't allow us to get overall coverage.

**Comment by wighawag** [comment]
If you can create such repo, it would be helpful
But yes remove `saveDeployments: true,`

**Comment by hickscorp** [comment]
@wighawag I can't create a repo now - I might be able to opensource our repository - would that work?
I removed `saveDeployments: true` - in fact I removed the whole `hardhat` network configuration.
No luck so far.

**Comment by hickscorp** [comment]
@wighawag You can try https://github.com/tableturn/tt-white-contracts/commit/0364008a7e40c77db426f0c86ebcec0609d9c447

**Comment by hickscorp** [comment]
@wighawag any idea?

**Comment by wighawag** [comment]
Did not have time yet to look at that, what are the step to reproduce ?

**Comment by hickscorp** [comment]
Simply run the test suite. If you run `yarn test`, the first test using the `Fast` diamond will succeed. Any subsequent test file using the `Fast` diamond will fail.
However, running test files individually works - eg `yarn test filename.test.ts`.

**Comment by hickscorp** [comment]
@wighawag Also - I think the rationale behind having `hardhat: { saveDeployments: false }` is wrong.
With `hardhat-deploy`, when I run `hardhat node` to have a local dev environment, my `deploy` script run.
If `saveDeployments` is set to `false`, then later if I use a `hardhat console --network localhost` to connect to my hardhat node, I cannot access any deployment state files, and things like `ethers.getContract('Something')` will fail...

**Comment by wighawag** [comment]
Hi @hickscorp I reproduced your issue locally but did not have time to see what is causing this issue yet.

Might be worth debugging to see what is happening.  hardhat-deploy fixture reset the blockchain state, but maybe some js variable are kept in memory and so the values changes when you execute one file test versus many.
