### ISSUE TITLE
Unable to deploy.

### ISSUE THREAD

**Issue by hickscorp** [wighawag/hardhat-deploy#337]
When trying to deploy our diamond contracts, we get the following error:

```
$ /path/node_modules/.bin/hardhat --network staging deploy
Nothing to compile
No need to generate any newer typings.
sending eth to create2 contract deployer address (0x3fab184622dc19b6109349b94811493bf2a45362) (tx: 0xa1b6b912160ec5fba1095876574bf712210e48e1f2338de3bc689a059044f735)...
deploying create2 deployer contract (at 0x4e59b44847b379578588920ca78fbf26c0b4956c) using deterministic deployment (https://github.com/Arachnid/deterministic-deployment-proxy)An unexpected error occurred:

Error: ERROR processing /path/deploy/10_deploySpc.ts:
Error: legacy pre-eip-155 transactions not supported (error={"name":"ProviderError","code":-32000,"_isProviderError":true}, method="sendTransaction", transaction="0xf8a58085174876e800830186a08080b853604580600e600039806000f350fe7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe03601600081602082378035828234f58015156039578182fd5b8082525050506014600cf31ba02222222222222222222222222222222222222222222222222222222222222222a02222222222222222222222222222222222222222222222222222222222222222", code=UNSUPPORTED_OPERATION, version=providers/5.6.8)
    at Logger.makeError (/path/node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
    at Logger.throwError (/path/node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
    at checkError (/path/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:119:16)
    at Web3Provider.<anonymous> (/path/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:603:20)
    at step (/path/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/path/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/path/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at DeploymentsManager.executeDeployScripts (/path/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1222:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async DeploymentsManager.runDeploy (/path/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1052:5)
    at async SimpleTaskDefinition.action (/path/node_modules/hardhat-deploy/src/index.ts:438:5)
    at async Environment._runTaskDefinition (/path/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at async Environment.run (/path/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at async SimpleTaskDefinition.action (/path/node_modules/hardhat-deploy/src/index.ts:584:32)
    at async Environment._runTaskDefinition (/path/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at async Environment.run (/path/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at async SimpleTaskDefinition.action (/path/node_modules/hardhat-deploy/src/index.ts:669:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by hickscorp** [comment]
So - it seems that the function trying to get the deployment proxy up and running is using this:

```
  public async getDeterministicDeploymentFactoryDeploymentTx(): Promise<string> {
    const info = await this.getDeterminisityDeploymentInfo();
    return (
      info?.signedTx ||
      '0xf8a58085174876e800830186a08080b853604580600e600039806000f350fe7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe03601600081602082378035828234f58015156039578182fd5b8082525050506014600cf31ba02222222222222222222222222222222222222222222222222222222222222222a02222222222222222222222222222222222222222222222222222222222222222'
    );
  }
```

On the hardhat network it seems because the fake hardhat network hasn't passed the EIP155 block.
On an existing chain, it's very likely that these contracts were deployed pre-EIP155 - so the transaction was accepted.
On a private chain though, it's a different story - EIP155 has "already happened" and this transaction isn't accepted (It might be missing the chain ID, as EIP155 is a counter-measure to cross-chain transaction replay attacks I think?)...

What do you advise?
Would it be possible to deploy the deployment contract ourselves, and somehow give its address to Hardhat when using `diamond.deploy(deterministicSalt: '0x...', deploymentProxyAddress: '0x....')?

**Comment by hickscorp** [comment]
Also - as we could start testing our contracts on our staging chain without having to deploy them deterministically, I've tried to deploy them without deterministic options. Well - it seems that `hardhat-deploy` is still trying to deploy the contract factory for `create2` even when not asked to use deterministic stuff.
Is there a way to deploy diamonds **without any deterministic routines involved**?

**Comment by hickscorp** [comment]
Since I cannot seem to deploy diamonds without deterministic deploys, I tried to dig deeper into how we could have our own deployment proxies. I ended up generating our own. In `hardhat.config.ts` it looks like something like this:

```typescript
  ...,
  networks: {
    hardhat: {
      live: false,
      // saveDeployments: true,
      tags: ['local', 'test']
    },
    localhost: {
      live: true,
      saveDeployments: true,
      tags: ['local'],
    },
    staging: {
      live: true,
      saveDeployments: true,
      url: nodeUrl('staging'),
      chainId: 18021981,
      accounts: accounts('staging'),
      tags: ['staging']
    },
    production: {
      live: true,
      saveDeployments: true,
      url: nodeUrl('production'),
      chainId: 18021982,
      accounts: accounts('production'),
      tags: ['staging']
    }
  },
  ...
```

Against all odds, this works great locally. It seems that `created2` is delegated properly to the factories using the signed transactions.
However when trying to deploy in one of our live chains, I get the following errors:

```
Error: ERROR processing /project/deploy/10_deploySpc.ts:
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0x717634cfe06FFAB2CEAA7fcf1b9019813f4B25FE","to":"0x13d35d4268ae26f2fD345c29A28182225aA9d10A","data":"0x...TRUNCATED, TOO LONG!!!","accessList":null}, error={"name":"ProviderError","code":-32000,"_isProviderError":true}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.6.8)
    at Logger.makeError (/project/node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
    at Logger.throwError (/project/node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
    at checkError (/project/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:78:20)
    at Web3Provider.<anonymous> (/project/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:603:20)
    at step (/project/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/project/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/project/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at DeploymentsManager.executeDeployScripts (/project/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1222:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async DeploymentsManager.runDeploy (/project/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1052:5)
    at async SimpleTaskDefinition.action (/project/node_modules/hardhat-deploy/src/index.ts:438:5)
    at async Environment._runTaskDefinition (/project/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at async Environment.run (/project/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at async SimpleTaskDefinition.action (/project/node_modules/hardhat-deploy/src/index.ts:584:32)
    at async Environment._runTaskDefinition (/project/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at async Environment.run (/project/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at async SimpleTaskDefinition.action (/project/node_modules/hardhat-deploy/src/index.ts:669:5)
error Command failed with exit code 1.
```

Any idea what could be happening? Is hardhat deploying the factory itself, or do I need to do anything?

**Comment by hickscorp** [comment]
A bit more information... I was able to get a tad further:

```
$ /project/node_modules/.bin/hardhat --network production deploy
Nothing to compile
No need to generate any newer typings.
sending eth to create2 contract deployer address (0x17AdB725223aEa5F990Fcdf1Cd02E3284F2ecc90) (tx: 0xd9eda6d0f72d59decae22841626699c012482c79694ee2b2f92867b2aa4f63c5)...
deploying create2 deployer contract (at 0x882eB7eD0758c5Db6DEd44a04655dFa252cfA521) using deterministic deployment (https://github.com/Arachnid/deterministic-deployment-proxy) (tx: 0x1ad3e523d54d7415274ad55929d0f63cfd3f9263c08277bfe6a10d94556d7667)...
deploying "SpcTopFacet"closed {"name":"SocketError","code":"UND_ERR_SOCKET","socket":{"bytesWritten":36625,"bytesRead":26422},"transactionHash":"0x08df44fb3a1817587e24bf30ad1f2ab79a50d79b6f29aaaee43debb52154b5d3"} SocketError: closed
    at TLSSocket.onSocketClose (/project/node_modules/undici/lib/client.js:967:31)
    at TLSSocket.emit (events.js:412:35)
    at TLSSocket.emit (domain.js:475:12)
    at net.js:686:12
    at TCP.done (_tls_wrap.js:564:7) {
  code: 'UND_ERR_SOCKET',
  socket: {
    localAddress: undefined,
    localPort: undefined,
    remoteAddress: undefined,
    remotePort: undefined,
    remoteFamily: undefined,
    timeout: undefined,
    bytesWritten: 36625,
    bytesRead: 26422
  },
  transactionHash: '0x08df44fb3a1817587e24bf30ad1f2ab79a50d79b6f29aaaee43debb52154b5d3'
}
An unexpected error occurred:

Error: ERROR processing /project/deploy/10_deploySpc.ts:
SocketError: closed
    at TLSSocket.onSocketClose (/project/node_modules/undici/lib/client.js:967:31)
    at TLSSocket.emit (events.js:412:35)
    at TLSSocket.emit (domain.js:475:12)
    at net.js:686:12
    at TCP.done (_tls_wrap.js:564:7)
    at DeploymentsManager.executeDeployScripts (/project/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1222:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async DeploymentsManager.runDeploy (/project/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1052:5)
    at async SimpleTaskDefinition.action (/project/node_modules/hardhat-deploy/src/index.ts:438:5)
    at async Environment._runTaskDefinition (/project/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at async Environment.run (/project/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at async SimpleTaskDefinition.action (/project/node_modules/hardhat-deploy/src/index.ts:584:32)
    at async Environment._runTaskDefinition (/project/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at async Environment.run (/project/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at async SimpleTaskDefinition.action (/project/node_modules/hardhat-deploy/src/index.ts:669:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Now the weirdest thing is happening - `hardhat console --network staging` works fine, and I can query balances for example.
But trying to deploy again gives me:

```
yarn run v1.22.17
$ /project/node_modules/.bin/hardhat --network staging deploy
Nothing to compile
No need to generate any newer typings.
An unexpected error occurred:

Error: ERROR processing /project/deploy/10_deploySpc.ts:
SocketError: closed
    at TLSSocket.onSocketClose (/project/node_modules/undici/lib/client.js:967:31)
    at TLSSocket.emit (events.js:412:35)
    at TLSSocket.emit (domain.js:475:12)
    at net.js:686:12
    at TCP.done (_tls_wrap.js:564:7)
    at DeploymentsManager.executeDeployScripts (/project/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1222:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async DeploymentsManager.runDeploy (/project/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1052:5)
    at async SimpleTaskDefinition.action (/project/node_modules/hardhat-deploy/src/index.ts:438:5)
    at async Environment._runTaskDefinition (/project/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at async Environment.run (/project/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at async SimpleTaskDefinition.action (/project/node_modules/hardhat-deploy/src/index.ts:584:32)
    at async Environment._runTaskDefinition (/project/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at async Environment.run (/project/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at async SimpleTaskDefinition.action (/project/node_modules/hardhat-deploy/src/index.ts:669:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jamesduncombe** [comment]
Related to https://github.com/rsksmart/rskj/issues/1805, dropping to v2.9.7 of HH seemed to fix it.

**Comment by hickscorp** [comment]
Yep - thanks @jamesduncombe !!!
