### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'gasUsed')

### ISSUE THREAD

**Issue by smallyunet** [wighawag/hardhat-deploy#399]
**Describe the bug**
Occur error when deploying the contract.

**versions**
 - hardhat-deploy [0.10.22]

**Additional context**
```
Error: ERROR processing /Users/smallyu/work/gogs/optimism-dev-env/packages/contracts/deploy/001-Lib_AddressManager.deploy.ts:
TypeError: Cannot read properties of null (reading 'gasUsed')
    at Object.tx.wait (/Users/smallyu/work/gogs/optimism-dev-env/packages/contracts/node_modules/hardhat-deploy/src/DeploymentsManager.ts:559:55)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async _deploy (/Users/smallyu/work/gogs/optimism-dev-env/packages/contracts/node_modules/hardhat-deploy/src/helpers.ts:668:21)
    at async _deployOne (/Users/smallyu/work/gogs/optimism-dev-env/packages/contracts/node_modules/hardhat-deploy/src/helpers.ts:1005:16)
    at async Object.deployFn [as func] (/Users/smallyu/work/gogs/optimism-dev-env/packages/contracts/deploy/001-Lib_AddressManager.deploy.ts:12:3)
    at async DeploymentsManager.executeDeployScripts (/Users/smallyu/work/gogs/optimism-dev-env/packages/contracts/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1219:22)
    at async DeploymentsManager.runDeploy (/Users/smallyu/work/gogs/optimism-dev-env/packages/contracts/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1052:5)
    at async SimpleTaskDefinition.action (/Users/smallyu/work/gogs/optimism-dev-env/packages/contracts/node_modules/hardhat-deploy/src/index.ts:438:5)
    at async Environment._runTaskDefinition (/Users/smallyu/work/gogs/optimism-dev-env/packages/contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
    at async Environment.run (/Users/smallyu/work/gogs/optimism-dev-env/packages/contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
    at DeploymentsManager.executeDeployScripts (/Users/smallyu/work/gogs/optimism-dev-env/packages/contracts/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1222:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DeploymentsManager.runDeploy (/Users/smallyu/work/gogs/optimism-dev-env/packages/contracts/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1052:5)
    at async SimpleTaskDefinition.action (/Users/smallyu/work/gogs/optimism-dev-env/packages/contracts/node_modules/hardhat-deploy/src/index.ts:438:5)
    at async Environment._runTaskDefinition (/Users/smallyu/work/gogs/optimism-dev-env/packages/contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
    at async Environment.run (/Users/smallyu/work/gogs/optimism-dev-env/packages/contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
    at async SimpleTaskDefinition.action (/Users/smallyu/work/gogs/optimism-dev-env/packages/contracts/node_modules/hardhat-deploy/src/index.ts:584:32)
    at async Environment._runTaskDefinition (/Users/smallyu/work/gogs/optimism-dev-env/packages/contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
    at async Environment.run (/Users/smallyu/work/gogs/optimism-dev-env/packages/contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
    at async SimpleTaskDefinition.action (/Users/smallyu/work/gogs/optimism-dev-env/packages/contracts/node_modules/hardhat-deploy/src/index.ts:669:5)
```

It is in `src/DeploymentsManager.ts:559:55` and the `receipt` looks null., but why? I can deploy the contract using the normal method.

**Comment by smallyunet** [comment]
I resolved this problem after adding param `numDeployConfirmations: 4`.
