### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by migoldfinger** [wighawag/hardhat-deploy#459]
**Describe the bug**
While setting up a huge repository with deployment I ran into this error
```
RangeError: Maximum call stack size exceeded
    at Array.values (<anonymous>)
    at recurseDependencies (E:\Workspaces\ExumaGroup\dfx-contracts\node_modules\hardhat-deploy\src\DeploymentsManager.ts:1164:45)
    at recurseDependencies (E:\Workspaces\ExumaGroup\dfx-contracts\node_modules\hardhat-deploy\src\DeploymentsManager.ts:1168:15)
    at recurseDependencies (E:\Workspaces\ExumaGroup\dfx-contracts\node_modules\hardhat-deploy\src\DeploymentsManager.ts:1168:15)
    at recurseDependencies (E:\Workspaces\ExumaGroup\dfx-contracts\node_modules\hardhat-deploy\src\DeploymentsManager.ts:1168:15)
    at recurseDependencies (E:\Workspaces\ExumaGroup\dfx-contracts\node_modules\hardhat-deploy\src\DeploymentsManager.ts:1168:15)
    at recurseDependencies (E:\Workspaces\ExumaGroup\dfx-contracts\node_modules\hardhat-deploy\src\DeploymentsManager.ts:1168:15)
    at recurseDependencies (E:\Workspaces\ExumaGroup\dfx-contracts\node_modules\hardhat-deploy\src\DeploymentsManager.ts:1168:15)
    at recurseDependencies (E:\Workspaces\ExumaGroup\dfx-contracts\node_modules\hardhat-deploy\src\DeploymentsManager.ts:1168:15)
    at recurseDependencies (E:\Workspaces\ExumaGroup\dfx-contracts\node_modules\hardhat-deploy\src\DeploymentsManager.ts:1168:15)
```

**To Reproduce**
1. Make a huge deployment with lots of dependencies
2. See error

**Expected behavior**
As long as I as a human can handle all dependencies so should a program.

**versions**
Version of Hardhat 2.15.0
Version Hardhat-deploy 0.11.30
Version of nodejs 18.16.0

**Additional context**
Repo: https://github.com/DFX-Protocol/dfx-contracts/tree/stackError
and I am not finished yet.....

**Comment by migoldfinger** [comment]
I had a circle reference though copy and paste
