### ISSUE TITLE
Method 'facets' not found when updating diamond

### ISSUE THREAD

**Issue by jo-es** [wighawag/hardhat-deploy#52]
I get the following error after running deploy the second time on a diamond. It seems like the Loupe facet is not registered / deployed in the initial deployment of the diamond.

buidler: 1.4.3
buidler-deploy: ^0.5.11

```sh
Error: ERROR processing /Users/johannes/Documents/dev/actus-protocol/ap-monorepo/packages/protocol/deploy/3-deploy-contracts.js:
Error: call revert exception (method="facets()", errorSignature=null, errorArgs=[null], reason=null, code=CALL_EXCEPTION, version=abi/5.0.3)
    at Logger.makeError (/Users/johannes/Documents/dev/actus-protocol/ap-monorepo/packages/protocol/node_modules/@ethersproject/logger/src.ts/index.ts:205:28)
    at Logger.throwError (/Users/johannes/Documents/dev/actus-protocol/ap-monorepo/packages/protocol/node_modules/@ethersproject/logger/src.ts/index.ts:217:20)
    at Interface.decodeFunctionResult (/Users/johannes/Documents/dev/actus-protocol/ap-monorepo/packages/protocol/node_modules/@ethersproject/contracts/node_modules/@ethersproject/abi/src.ts/interface.ts:326:23)
    at Contract.<anonymous> (/Users/johannes/Documents/dev/actus-protocol/ap-monorepo/packages/protocol/node_modules/@ethersproject/contracts/src.ts/index.ts:291:44)
    at step (/Users/johannes/Documents/dev/actus-protocol/ap-monorepo/packages/protocol/node_modules/@ethersproject/contracts/lib/index.js:46:23)
    at Object.next (/Users/johannes/Documents/dev/actus-protocol/ap-monorepo/packages/protocol/node_modules/@ethersproject/contracts/lib/index.js:27:53)
    at fulfilled (/Users/johannes/Documents/dev/actus-protocol/ap-monorepo/packages/protocol/node_modules/@ethersproject/contracts/lib/index.js:18:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at DeploymentsManager.runDeploy (/Users/johannes/Documents/dev/actus-protocol/ap-monorepo/packages/protocol/node_modules/buidler-deploy/src/DeploymentsManager.ts:851:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
```

**Comment by wighawag** [comment]
Could you try with the latest version of buidler-deploy (0.6.0-beta.36) ?

Or at least version 0.5.18

Also if you have a reproduction repo, that will be very helpful.

Note that the version of Diamond that buidler-deploy uses has the Loupe facet builtin. so not sure what causing the error

**Comment by jo-es** [comment]
Bumped to 0.6.0-beta.36 but experiencing the same error.
Here is a link to the buidler-deploy script in the example repo: [atpar/protocol](https://github.com/atpar/ap-monorepo/blob/feature/AP-695-diamond/packages/protocol/deploy/3-deploy-contracts.js#L41)

**Comment by wighawag** [comment]
do you reset ganache each time ?
If so this is normal behavior. --reset is needed to ensure past deployments are not considered

**Comment by jo-es** [comment]
Ok that makes sense. But I would expect for the non-diamond contracts to throw the same error.

**Comment by wighawag** [comment]
for other contract, they would not fail on deploy, but if you try to call a function on them (like .facets() for diamond) it will also fails
unless the contract code changed which would then trigger a deployment

**Comment by wighawag** [comment]
actually I forgot, maybe the deployment is always executed because the tx hash for the previous deployment is not found.

**Comment by jo-es** [comment]
> actually I forgot, maybe the deployment is always executed because the tx hash for the previous deployment is not found.
Yes. We do call some methods in the deployment workflow and they all succeed. 

Thanks. You can close the issue.
