### ISSUE TITLE
trying to deploy and get maximum call stack error 

### ISSUE THREAD

**Issue by ethereumdegen** [wighawag/hardhat-deploy#523]
**Describe the bug**

RangeError: Maximum call stack size exceeded
    at Array.values (<anonymous>)
    at recurseDependencies (/.../packages/contracts/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1168:45)
    at recurseDependencies (/.../packages/contracts/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1172:15)
    at recurseDependencies (/.../packages/contracts/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1172:15)
    at recurseDependencies (/.../packages/contracts/node_modules/hardhat-deploy/src/
...

**To Reproduce**

run 'deploy' with many contracts 

**Expected behavior** 

no error

**versions**
 - hardhat-deploy v 0.11.34
 - hardhat  v2.16.1
 - nodejs  v16 

**Additional context**

**Comment by ethereumdegen** [comment]
had infinite dependency loop
