### ISSUE TITLE
Command `hardhat node` fails in `hardhat-deploy@0.13.0`

### ISSUE THREAD

**Issue by guidanoli** [wighawag/hardhat-deploy#558]
**Describe the bug**
Running `hardhat node` fails with the following error message and stack trace:
```
Error HH604: Error running JSON-RPC server: ERROR processing deploy/01_input.ts:
TypeError: network.provider.getSignerFrom is not a function
    at getFrom (node_modules/.pnpm/hardhat-deploy@0.13.0/node_modules/hardhat-deploy/src/helpers.ts:1708:28)
    at fetchIfDifferent (node_modules/.pnpm/hardhat-deploy@0.13.0/node_modules/hardhat-deploy/src/helpers.ts:857:34)
    at async _deployOne (node_modules/.pnpm/hardhat-deploy@0.13.0/node_modules/hardhat-deploy/src/helpers.ts:942:24)
```

**To Reproduce**
1. Clone [cartesi/rollups-contracts](https://github.com/cartesi/rollups-contracts) at `4f0355f`
2. Run `pnpm install`
3. Run `pnpm exec hardhat node`

**Expected behavior**
The same as with `hardhat-deploy@0.12.4`:
```
sending eth to create2 contract deployer address (0xE1CB04A0fA36DdD16a06ea828007E35e1a3cBC37) (tx: 0x01b97e202bf5df0889fdc6a13455f5b1b1a491edbd970f68e5247118cfd7ffa3)...
deploying create2 deployer contract (at 0x914d7Fec6aaC8cd542e72Bca78B30650d45643d7) using deterministic deployment (https://github.com/Arachnid/deterministic-deployment-proxy) (tx: 0x41a6b731f53cf45627c3976abcb9ecd52fb2142f8f6fbbff4e0bb54a9b3667bc)...
deploying "InputBox" (tx: 0x13aa647b0352b1633f1d6e1ed05cb7faff1db819ecef47bd27e23197f25f7a00)...: deployed at 0x593E5BCf894D6829Dd26D0810DA7F064406aebB6 with 275862 gas
deploying "EtherPortal" (tx: 0xf1d3b1b7205e7265596efbd2c0462cad5b089ea868c599ad1f5b62af74431d05)...: deployed at 0xfa2292f6D85ea4e629B156A4f99219e30D12EE17 with 238142 gas
deploying "ERC20Portal" (tx: 0x074db215ad483c2528e8f5265e370d215c375de4dddcf35991dfb0da0755c549)...: deployed at 0xB0e28881FF7ee9CD5B1229d570540d74bce23D39 with 269088 gas
deploying "ERC721Portal" (tx: 0x30780c74d8e91d60db1283b079941f512f80cb3fa7f26acaddf103762247b3d6)...: deployed at 0x874b3245ead7474Cb9f3b83cD1446dC522f6bd36 with 308450 gas
deploying "ERC1155SinglePortal" (tx: 0x190d4c4dc1515667beaa1e348762321ec0c02645dfadd2908802739a23fd1bc9)...: deployed at 0x2f0D587DD6EcF67d25C558f2e9c3839c579e5e38 with 317542 gas
deploying "ERC1155BatchPortal" (tx: 0x5100d3ffdcfb915ac1486c7b64dd431b1d5518afa860d27ad4c8a311a07855d8)...: deployed at 0x4a218D331C0933d7E3EB496ac901669f28D94981 with 370950 gas
deploying "AuthorityFactory" (tx: 0x1a4b3bfcf32601f55520e130d677961afc02d7bc68153934929ed2e6d91bee15)...: deployed at 0xB897F7Fe78f220aE34B7FA9493092701a873Ed45 with 532228 gas
deploying "QuorumFactory" (tx: 0x298bd3bbdcce24f4a1b5a89e3a942e7374afdd6e49664e5aa9d18b0ce7c62e83)...: deployed at 0x22AFD9162079c7Ac0aF874054298Bf46F29157F1 with 747585 gas
deploying "ApplicationFactory" (tx: 0xd0ac8ed1b31a44e41b42ac16d36e22a32d11b9df89977098fcbb67140e86e545)...: deployed at 0x1d4CfBD2622d802A07CeB4C3401Bbb455c9dbdC3 with 1273228 gas
deploying "SelfHostedApplicationFactory" (tx: 0xb9600fbd429f28e71f238c82d103a35ebb803218c306d82d8f6814eeff541ab0)...: deployed at 0x4C11C7F82D6D56a726f9B53dd99af031AFd86BB6 with 287274 gas
deploying "SafeERC20Transfer" (tx: 0x4562abf20c61162b6fa32760fa9664dca7aecb97283a08645d12bcb1c68ca4b3)...: deployed at 0x817b126F242B5F184Fa685b4f2F91DC99D8115F9 with 227912 gas
```

**versions**
 - hardhat-deploy 0.13.0
 - hardhat 2.22.4
 - nodejs 20.17.0

**Comment by guidanoli** [comment]
@wighawag

**Comment by wighawag** [comment]
I reverted the zksync change, published in 0.14.0, see coment : https://github.com/wighawag/hardhat-deploy/pull/555#discussion_r1806045979

**Comment by wighawag** [comment]
Thanks for reporting!

**Comment by guidanoli** [comment]
Thanks for the quick response! :blush:
