### ISSUE TITLE
Unhelpful error when "execute" fails

### ISSUE THREAD

**Issue by dmihal** [wighawag/hardhat-deploy#67]
When an `execute` call fails, an unhelpful error is thrown, that makes it difficult to debug:

```
Error: ERROR processing /deploy/deployment.js:
ProviderError: The execution failed due to an exception.
    at HttpProvider.request (node_modules/hardhat/src/internal/core/providers/http.ts:46:19)
    at HDWalletProvider.request (node_modules/hardhat/src/internal/core/providers/accounts.ts:131:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at DeploymentsManager.executeDeployScripts (node_modules/hardhat-deploy/src/DeploymentsManager.ts:991:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I wonder if it's possible to pre-generate an error, so that the stack trace points to the failing call in the deployment script

**Comment by wighawag** [comment]
I agree, I would like to improve that.
Need to look into it. If you have ideas, feel free to make a PR or propose some outline

**Comment by bghughes** [comment]
I have run into the same issue.

**Comment by Dylan-Kerler** [comment]
+1 no idea what is going on. Error message is way too vague
